### ISSUE TITLE
Investigate Video SDP Send Parameters on Chrome for Android

### ISSUE THREAD

**Issue by robertlong** [mozilla/mr-social-client#20]
Error seen on Chrome for Android 52:
```
Failed to set remote video description send parameters..
```

This occurs on this line: https://github.com/mozilla/naf-janus-adapter/blob/master/src/index.js#L245

SDP sent by Janus:
```
v=0
↵o=- 1511245988964004 1 IN IP4 54.67.121.231
↵s=Janus session
↵t=0 0
↵a=group:BUNDLE audio video
↵a=msid-semantic: WMS janus
↵m=audio 9 RTP/SAVPF 111
↵c=IN IP4 54.67.121.231
↵a=sendonly
↵a=mid:audio
↵a=rtcp-mux
↵a=ice-ufrag:r58T
↵a=ice-pwd:w0+1h6bBhREj4nDqKLrtKB
↵a=ice-options:trickle
↵a=fingerprint:sha-256 40:F7:B1:3D:F9:1E:04:B8:FF:5F:FF:5F:25:75:EB:C0:ED:F3:25:06:49:1F:AE:B4:E7:7A:BE:69:2F:DA:CA:B2
↵a=setup:actpass
↵a=rtpmap:111 opus/48000/2
↵a=ssrc:3516440168 cname:janusaudio
↵a=ssrc:3516440168 msid:janus janusa0
↵a=ssrc:3516440168 mslabel:janus
↵a=ssrc:3516440168 label:janusa0
↵a=candidate:1 1 udp 2013266431 54.67.121.231 47417 typ host
↵a=end-of-candidates
↵m=video 9 RTP/SAVPF 107
↵c=IN IP4 54.67.121.231
↵a=sendonly
↵a=mid:video
↵a=rtcp-mux
↵a=ice-ufrag:r58T
↵a=ice-pwd:w0+1h6bBhREj4nDqKLrtKB
↵a=ice-options:trickle
↵a=fingerprint:sha-256 40:F7:B1:3D:F9:1E:04:B8:FF:5F:FF:5F:25:75:EB:C0:ED:F3:25:06:49:1F:AE:B4:E7:7A:BE:69:2F:DA:CA:B2
↵a=setup:actpass
↵a=rtpmap:107 H264/90000
↵a=fmtp:107 profile-level-id=42e01f;packetization-mode=1
↵a=rtcp-fb:107 ccm fir
↵a=rtcp-fb:107 nack
↵a=rtcp-fb:107 nack pli
↵a=rtcp-fb:107 goog-remb
↵a=ssrc:1447368931 cname:janusvideo
↵a=ssrc:1447368931 msid:janus janusv0
↵a=ssrc:1447368931 mslabel:janus
↵a=ssrc:1447368931 label:janusv0
↵a=candidate:1 1 udp 2013266431 54.67.121.231 47417 typ host
↵a=end-of-candidates
```

It's having an issue with the video part, so it doesn't like something in or after this line `m=video 9 RTP/SAVPF 107`.

This SDP is created by Janus here: https://github.com/mozilla/janus-plugin-sfu/blob/master/src/lib.rs#L437

**Comment by mquander** [comment]
No offense, but why are you assigning this issue to me when I'm on vacation
for a week? I don't have any special expertise that makes it totally
obvious I will do this work, and it's not even clear that it's a high
priority (do we have a use case for Android users sending video?)

I prefer to have assignment mean "person X is definitely doing this work"
rather than "person X might do this work at some point in the future." The
first is useful because it tells you things like "person X is the expert on
this issue, ask them if you want to know about it" and "don't start working
on this because person X is doing it already." I'm not sure what the second
is useful for.

Let me know if you disagree and I'm happy to consider another way.

**Comment by mquander** [comment]
(On reading, I see that it's about receiving video, not sending, so I agree
that this is worth doing in the near future sometime. But I won't work on
it e.g. before fixing Janus Websocket stability.)

**Comment by netpro2k** [comment]
This was done on the client which is good enough for MVP. We want to have the server handle this in the future.
