### ISSUE TITLE
Microsoft Edge hangs on connect

### ISSUE THREAD

**Issue by robertlong** [mozilla/mr-social-client#26]
No errors are emitted. However it looks like its getting hung up in `naf-janus-adapter`'s `createPublisher()` method.

**Comment by brianpeiris** [comment]
Microsoft Edge does not support WebRTC data channels. They [list is as "under consideration"](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rtcdatachannels/?q=rtc%20data). This is a blocker for us. See https://github.com/mozilla/socialmr/issues/73 for a workaround for Windows MR headsets.

**Comment by machenmusik** [comment]
isn't there a way to use webrtc for media but websocket for data?

**Comment by brianpeiris** [comment]
Yeah, we can probably fallback to websockets, but it's probably not worth our time at the moment, especially since there is a workaround with SteamVR + Firefox. In the long term I think the overhead with websockets will be limiting, compared to a UDP data channel, so I'd rather push the Edge team to implement data channels.
